### ISSUE TITLE
Default to colon separation

### ISSUE THREAD

**Issue by corysimmons** [rossPatton/stylint#107]
This is already the standard amongst a lot of core Stylus lib contributors, and will be the only way you can use Stylus at `rc-1.0.0` https://github.com/stylus/stylus/wiki/1.0.0#what-to-change-in-syntax

**Comment by eric-adstage** [comment]
Damn, I was really liking those typing-one-less-character time savings I was getting all over the place :) But I can see how it would make parsing more difficult.

**Comment by corysimmons** [comment]
> it would make parsing more difficult

That's always been the argument against it. I think the preferred syntax is now:

```stylus
.foo
  background: red
```

Variables should also be prefixed with a `$` but that's a story for another issue I suppose.

**Comment by corysimmons** [comment]
Also if you're using Emmet you can modify your settings for it (since the Emmet maintainer refuses to update it's default from colon-less to colon even with the Stylus maintainer chiming in..) in any editor so it expands with the colon. So if you use Emmet you're not saving time by omitting the colon.

**Comment by rossPatton** [comment]
If that's the direction stylus is going I don't mind changing it eventually. I personally like the lack of colons myself, but I can definitely relate to it being painful to develop around.

**Comment by rossPatton** [comment]
@corysimmons https://github.com/rossPatton/stylint/issues/108

By the way, how actively developed is stylus at the moment? That 1.0.0 wiki you linked was from 2013.

**Comment by corysimmons** [comment]
@rossPatton It's actively developed (https://github.com/stylus/stylus/commits/master). I'm not sure how close they are to `1.0.0` but if colons are the way [most](https://github.com/declandewet/stylus-conventions#which-syntax) [of](https://github.com/jenius/axis/tree/master/axis) [the](https://github.com/mojotech/jeet/tree/master/stylus/jeet) [rest](https://github.com/tj/nib/tree/master/lib/nib) [of](https://github.com/voronianski/dookie-css/tree/master/lib) the community is moving, then it seems like good idea to go ahead and default to it.

**Comment by rossPatton** [comment]
1.0 is out and now defaults to colon separation

**Comment by corysimmons** [comment]
:+1:

**Comment by rossPatton** [comment]
Aaaaaand there are a few issues, created a new issue for those
