### ISSUE TITLE
Stylint 1.0.0

### ISSUE THREAD

**Issue by rossPatton** [rossPatton/stylint#108]
Hey everyone,

Stylint is getting close to a 1.0.0 release. With any luck it'll be out within the next month or two, depending on my schedule and how much time I can find to work on it.

1.0.0 represents a major revamp under the hood, and will add many new features (some of which might not be fully implemented yet). The amount of code was cut nearly in half despite adding many new checks, it runs much faster, and coverage is near 100%.

I've created a 1.0.0 milestone here: https://github.com/rossPatton/stylint/milestones/1.0.0 and a branch here: https://github.com/rossPatton/stylint/tree/stylint-1.0.

Want to help? Those of you feeling adventurous can check out the 1.0.0 branch and put it through the paces against your own code, and reporting any issues you find.

I've created a label specifically for this, please use it when reporting issues that only apply to the 1.0 branch.

You'll also see that i've added help wanted labels to the 1.0.0 issues. Anything yall can do to contribute here would help me get 1.0.0 out the door faster. 

My end game here is to have a linter that's as stable and powerful as jshint/jscs, so that I can finally devote more of my time to other projects :)

Thanks!

**Comment by awayken** [comment]
I've updated my local copy and checked out the stylint-1.0 branch. I ran `npm install` but is there anything else I should do to update my local copy to make it ready to use?

**Comment by rossPatton** [comment]
Yep! 

If you run `npm install . -g` inside the 1.0 branch, you should be able to run stylint 1.0 from the cli anywhere on your machine. This will let you it against any stylus you write and make sure it's still performing as it should.
