### ISSUE TITLE
Regex to remove comments clashing with file globbing - causing hanging process

### ISSUE THREAD

**Issue by jackbrewer** [rossPatton/stylint#110]
### Problem

I've run in to an issue when using Stylus [file globbing](https://learnboost.github.io/stylus/docs/import.html#file-globbing) for `@import` and `@require`. 

Stylint process can hang indefinitely, using 100% CPU (depending on file length, and the location of the glob within the file).

Example:
`@require 'components/*'`

### Diagnosis

It seems the [regex in `parse.js`](https://learnboost.github.io/stylus/docs/import.html#file-globbing) is catching the trailing `/*` of the above line and is treating it as an opening comment. As it can never find a closing comment, it keeps searching through subsequent lines, getting exponentially slower. Multiple globs in a file makes things worse.

The following gif shows a stripped back example - you can see the 'steps' in the top-right ~doubling with each new-line.

![runaway-regex](https://cloud.githubusercontent.com/assets/720908/8057537/05351868-0eaa-11e5-895a-521cf6ddef8f.gif)

Live Example - https://regex101.com/r/jU0eJ2/1

### Solution

New regex which accounts for this edge-case. I know @benedfit is taking a look at possible fix, but we're finding it hard to find a solution which doesn't introduce another edge-case where an actual comment gets missed, so I thought I'd raise here in the meantime.

**Comment by benedfit** [comment]
I'm playing around with a Regex that might fix this problem: https://regex101.com/r/zM0xA6/1, and including some extra test cases that might not have been previously tested against. I'll update you with my progress

**Comment by benedfit** [comment]
@rossPatton https://regex101.com/r/zM0xA6/3 is close, but it wouldn't remove comments in the format `/*'word'*/`

**Comment by benedfit** [comment]
https://regex101.com/r/zM0xA6/6 has cracked it. Going to submit a PR shortly

**Comment by rossPatton** [comment]
Weird, i've never hit this issue personally (and I use globs when I require) but it's awesome to see that it's already been resolved!

**Comment by jackbrewer** [comment]
Yeah, it's a strange one. File length definitely plays a part. Our index stylus file (mainly just @requires) is well commented/documented so is 100 lines+. It was only here that we've spotted the issue.

**Comment by rossPatton** [comment]
Interesting, I'll try to merge it in tonight.

**Comment by rossPatton** [comment]
@benedfit @jackbrewer  update on this, i took a look at the pr, tests passed, looked okay, merged it into develop, but after messing with it more it seems to break things. Playing around with it in regexr, it doesn't seem to match the same way the old regex matched.

I ended up tweaking the existing one, which seems to solve the problem: (see here)[https://regex101.com/r/zY7fR9/1]

It's on develop now, if you want to pull and take a look.

**Comment by benedfit** [comment]
@rossPatton just took a look; the new regex will ignore comments that start on the same line as an other Stylus, see https://regex101.com/r/zY7fR9/3. Is that the desired outcome?

**Comment by jackbrewer** [comment]
Tested develop and all seems to be working well. Happy to test again based on the outcome of the above comment ^

**Comment by rossPatton** [comment]
What about this? https://regex101.com/r/zY7fR9/4

**Comment by rossPatton** [comment]
I've also pushed this change up to develop, if you want to test that way.

**Comment by rossPatton** [comment]
@benedfit @jackbrewer

**Comment by benedfit** [comment]
@rossPatton tested it and it works well

**Comment by rossPatton** [comment]
Excellent!

**Comment by jackbrewer** [comment]
:+1: Tested new develop changes and still fixed and working as expected.

**Comment by rossPatton** [comment]
0.9.10 fixes this issue, sorry it took so long
