### ISSUE TITLE
using "mixed" in .stylintrc results in warnings

### ISSUE THREAD

**Issue by olegskl** [rossPatton/stylint#126]
Using Stylint 1.0.6 on OSX with .stylintrc containing either

```stylus
{"mixed": true}
```
or
```stylus
{"mixed": false}
```
the following code
```stylus
.foo {
  color: red;
}
```
produces a warning:

> Warning: mixed spaces and tabs
File: app/bundles/logged-site/logged-site.styl
Line: 2: color: red;

There are two spaces before `color:` and one space before `red;`.
Removing the rule from .stylintrc makes the error go away.

**Comment by rossPatton** [comment]
i can't replicate this issue. it's working properly for me. what's the rest of your config look like?

**Comment by olegskl** [comment]
There's no "the rest of my config". That's all the code I have.

**Comment by olegskl** [comment]
Looks to be the same issue as #127.
