### ISSUE TITLE
"commentSpace" check produces no warnings

### ISSUE THREAD

**Issue by olegskl** [rossPatton/stylint#128]
Using Stylint 1.0.6 on OSX with .stylintrc containing
```json
{"commentSpace":"always"}
```
the following code
```stylus
//comment-without-space
// comment-with-space
.foo {}
```
produces no warning whatsoever:
> Stylint: You're all clear!

**Comment by rossPatton** [comment]
try 1.0.8, lemme know if you still have issues

**Comment by rossPatton** [comment]
@olegskl Was your issue resolved?

**Comment by olegskl** [comment]
I don't know. We decided to abandon stylint, so I haven't checked the latest fixes.

**Comment by rossPatton** [comment]
:(
