### ISSUE TITLE
Colon validator throws error with with multiple selectors and @import/@media statements

### ISSUE THREAD

**Issue by anthonyjruffa** [rossPatton/stylint#130]
When using this setting (stylint version 1.0.7):

`"colons" : {
    "expect" : "always",
    "error" : true
  }`

It throws this error:
`Error: missing colon between property and value`

This happens when working with multiple selectors and using import and media statements.

Examples:

`Error: missing colon between property and value
File: <path-to-file>
Line: <line-number>: @media (....)`

`Error: missing colon between property and value
File: <path-to-file>
Line: <line-number>: @import <name-of-file>`

`Error: missing colon between property and value
File: <path-to-file>
Line: <line-number>: .class-name a`

**Comment by rossPatton** [comment]
Try 1.0.8, lemme know if you still have issues

**Comment by anthonyjruffa** [comment]
Thank you for your response and the update.

I ran version 1.0.8 and got this error:

`<path-to-node_modules-dir>/node_modules/stylint/src/core/setState.js:40
		this.state.conf = this.config.commentSpace.expect || this.config.commentSpac
		                                          ^
TypeError: Cannot read property 'expect' of undefined
    at Object.setState (<path-to-node_modules-dir>/node_modules/stylint/src/core/setState.js:40:45)
    at Object.<anonymous> (<path-to-node_modules-dir>/node_modules/stylint/src/core/parse.js:35:16)
    at Array.forEach (native)
    at Object.<anonymous> (<path-to-node_modules-dir>/node_modules/stylint/src/core/parse.js:30:9)
    at Array.forEach (native)
    at Object.parse (<path-to-node_modules-dir>/node_modules/stylint/src/core/parse.js:18:13)
    at <path-to-node_modules-dir>/node_modules/stylint/node_modules/async/lib/async.js:254:17
    at done (<path-to-node_modules-dir>/node_modules/stylint/node_modules/async/lib/async.js:135:19)
    at <path-to-node_modules-dir>/node_modules/stylint/node_modules/async/lib/async.js:32:16
    at <path-to-node_modules-dir>/node_modules/stylint/node_modules/async/lib/async.js:251:21`

If you like, I can try to fix this and open a PR.

**Comment by rossPatton** [comment]
Hmm, i'm not getting that. But In looking at that code again I do see a mistake, pretty glaring.

I need to make sure we're even running the commentSpace check at all before I do any of the work there. Like what I do in lint.js.

I'll take another stab at it tonight but if you want to submit a PR i'd gladly accept it.

**Comment by anthonyjruffa** [comment]
Ah OK.  No need to rush a fix.  I will take a good look at this either tonight or tomorrow.

Thank you again!

**Comment by rossPatton** [comment]
Cool. Yeah the 'always' checks are new and haven't been as thoroughly tested as the other checks are. But luc

**Comment by rossPatton** [comment]
hey, i went ahead and (hopefully) fixed it in 1.0.9, lemme know if things work now

**Comment by anthonyjruffa** [comment]
Thank you for the update.  The commentSpace error went away but the original issue returned.

I took a look and after some changes fixed some of the errors, but not all of them.  I will continue to work on this and will open a PR when I am done.

**Comment by rossPatton** [comment]
:+1:
