### ISSUE TITLE
Check method spec ambiguity

### ISSUE THREAD

**Issue by xdissent** [rossPatton/stylint#135]
The contribution docs say checks should return `true|false` to indicate pass/fail, but in reality they must call `this.msg()` to actually add a failure. It looks like the return value is only used in tests at this point.

My question is, given a check like `none()`, should the return value be `true` if `border: none` is found **regardless of the config** (`always|never` etc)? In other words, should the config only affect error messages and *not* return value for checks that accept a config?

Many of the tests manipulate `app.state.conf`, but never actually check for error messages (only return value), rendering them pretty ineffective (there's a bug in `none()` right now when config is `always` for example). If you can clear that up, I'll gladly take a pass at improving the tests and/or docs!

**Comment by rossPatton** [comment]
" In other words, should the config only affect error messages and not return value for checks that accept a config?

Yep

Checking error messages sounds like a good idea, do whatever you want!

**Comment by rossPatton** [comment]
@xdissent Lemme know if you have some work on this already, I was going to just go ahead and starting adding in the error message tests

**Comment by xdissent** [comment]
Not yet! If you get it started I'll join in though

**Comment by rossPatton** [comment]
cool cool

**Comment by rossPatton** [comment]
improve-test-cases will be the branch
