### ISSUE TITLE
Media query causes false positive when colons is set to 'never'

### ISSUE THREAD

**Issue by bzalasky** [rossPatton/stylint#158]
Stylus requires colons in media queries when you specify max-width, min-width, etc...

    @media screen and (max-width: 1183px)

 Stylint misinterprets this, generating a ton of noise, which makes legitimate warnings difficult to spot. For the record, I prefer colons set to 'always' but it wasn't my call to make on the project in question.

**Comment by bzalasky** [comment]
I've worked around this at the moment by pulling in Rupture to handle media queries via block mixins, but this would still be good to fix.

**Comment by rossPatton** [comment]
Course, it'll definitely get fixed

**Comment by rossPatton** [comment]
1.0.10 is out now, this issue should be fixed. Lemme know if you still have issues.
