### ISSUE TITLE
Property not valid, false positives on pointer-events, vendor-prefixed properties and complex selectors

### ISSUE THREAD

**Issue by bzalasky** [rossPatton/stylint#159]
This is happening for pointer-events, vendor-prefixed properties, and also some complex selectors. Here are some examples (just listing them for reference, they're not like this in the source)...

    table&
    &[disabled]
    + a
    + span
        pointer-events none
        -khtml-user-select none
        -webkit-touch-callout none

**Comment by rossPatton** [comment]
this is mostly cleaned up in develop, will hopefully go out with 1.0.10

**Comment by bzalasky** [comment]
Great. Thanks for the quick response.

**Comment by rossPatton** [comment]
1.0.10 is out now, this issue should be fixed. Lemme know if you still have issues.
