### ISSUE TITLE
Linting code string

### ISSUE THREAD

**Issue by Semigradsky** [rossPatton/stylint#160]
Hi! Is there any way linting code string? Something like this:
```js
const code = '.className padding 0';

const stylint = require('stylint')({
    brackets: 'always',
    namingConvention: 'BEM',
    semicolons: 'always'
}).create();

const errors = stylint.lint(code);
```
It would be great!

---
Linter like CSSLint, ESLint, JSHint allow it.

**Comment by rossPatton** [comment]
It doesn't currently exist but it's something that will probably be added soon.

See: https://github.com/rossPatton/stylint/issues/146

**Comment by Semigradsky** [comment]
Nice!

**Comment by rossPatton** [comment]
gonna close this since it's a dupe of #146
