### ISSUE TITLE
Trailing Whitespace docs

### ISSUE THREAD

**Issue by joezimjs** [rossPatton/stylint#178]
The docs currently refer to the `trailingWhitespace` rule as just "whitespace" (https://github.com/rossPatton/stylint#whitespace--default-true-true--false-). It also says in the docs that the possible values are `true` or `false`, but I know that it uses `"never"`. I'd fix this myself, but I'm not 100% certain what the possible values are. I assume it's just `"never"` and `false`.

**Comment by rossPatton** [comment]
ah, you would be correct. it's 'never' (as in, never allow whitespace) and false (as in, we dont check for this).
