### ISSUE TITLE
Plz add to whitelist

### ISSUE THREAD

**Issue by yoyurec** [rossPatton/stylint#183]
https://css-tricks.com/snippets/css/remove-gray-highlight-when-tapping-links-in-mobile-safari/
```
... {
    -webkit-tap-highlight-color ...
}
```
*property is not valid*

-----
http://caniuse.com/#feat=css-placeholder
```
::placeholder {
    ...
}
```
*unecessary colon found*

-----
https://developer.mozilla.org/en-US/docs/Web/CSS/@media
```
@page {
    ...
}
```
*property is not valid*

**Comment by rossPatton** [comment]
hi, i will get to this over the weekend most likely, but if you want to just submit a PR against develop i'll gladly merge it in right away

**Comment by rossPatton** [comment]
this has been pushed up
