### ISSUE TITLE
@stylint off doesn't seem to be doing anything

### ISSUE THREAD

**Issue by lellimecnar** [rossPatton/stylint#196]
I'm putting: `// @stylint off` at the top of some of my files, and they're still being linted. Those files are also wrapped in `@css { ... }` but that seems to be ignored as well.

**Comment by rossPatton** [comment]
could you include a sample of your stylus please

**Comment by lellimecnar** [comment]
The files in having difficulties with are just jQuery UI CSS files, wrapped in `@css`. That didn't work to bypass stylint, so I added `// @stylint off` on the first line, which didn't work either.

**Comment by rossPatton** [comment]
good to know, either one of those options should have worked. i use `@stylint off` in my code all the time. i'll look into it

**Comment by rossPatton** [comment]
should be resolved in 1.2.3
