### ISSUE TITLE
duplicates: true, globalDupe: false not working

### ISSUE THREAD

**Issue by jcrosetto** [rossPatton/stylint#201]
I have a stylus file (myfile.styl) with the following in it:

    .left-panel
    	border green

    .left-panel
    	border green
    	border blue

If I set duplicates: true and globalDupe: false, running the following does not produce any errors.

    var gulp = require('gulp');
    var stylint = require('gulp-stylint');

    gulp.task('default', function () {
        return gulp.src('src/myfile.styl')
            .pipe(stylint())
    });

If I set globalDupe: true then the duplicate errors are thrown as they should be.

**Comment by rossPatton** [comment]
this will be fixed in the next release
