### ISSUE TITLE
Search parent directories for .stylintrc file

### ISSUE THREAD

**Issue by servel333** [rossPatton/stylint#208]
Use Case: I'm using Sublime Text 3 with Sublime Linter. This tool will change the directory to the same directory of the file being linted by default (not my project directory, but a subdirectory). I would like to put my `.stylintrc` file in the root of my project but I can't because stylint only looks in the working directory.

I would like to request that the linter start searching in the directory of the file being linted and then search parent directories for `.stylintrc` files instead of searching the working directory (perhaps it could also search the working directory to allow for backwards compatibility).

This is a pretty common behavior for linters that I've used. For example, JSHint has this description in the [docs](http://jshint.com/docs/):

> JSHint will start looking for this file in the same directory as the file that's being linted. If not found, it will move one level up the directory tree all the way up to the filesystem root. 

As a bonus, it would be nice if the current user's home directory was also searched for a `.stylintrc` file.

**Comment by rossPatton** [comment]
this will be in the next release

**Comment by servel333** [comment]
Awesome. Thanks.

**Comment by rossPatton** [comment]
@servel333 so i've added similar behavior. right now the new order of priority is:

1 using stylint programmatically and passing in config option as a parameter

2 using stylint via command line and passing in a path to a .stylintrc via the --config flag

3 if the first two fail, stylint will then check the cwd

4 if that fails, stylint will walk up 2 directories looking for a .stylintrc file

5 if THAT fails, it checks the home directory

6 if still nothing, and no errors happened during all this, it will just use the default config

**Comment by servel333** [comment]
> 4 if that fails, stylint will walk up 2 directories looking for a .stylintrc file

Why does it only walk up two directories?

**Comment by rossPatton** [comment]
i suppose i could make it walk all the way up

**Comment by servel333** [comment]
I think two directories up will satisfy most users, but deeply nested style files isn't unheard of if, for example, you had a Git submodule in your project. I think I would recommend walking all the way up if it doesn't significantly affect the performance of the application. Thanks.
