### ISSUE TITLE
Code-style false-positives inside content rules

### ISSUE THREAD

**Issue by dennishall1** [rossPatton/stylint#217]
If you have `content: ",";` --- you'll get a false-positive:
Warning: commas must be followed by a space for readability.
File: ./src/modules/filename.styl
Line: 182: content: ",";

This would also apply for other rules that might get triggered, but shouldn't, inside `content` style rules, such as colons and semicolons, maybe even comments, others.  But commas will likely be the most common false-positives.

**Comment by rossPatton** [comment]
this issue should be fixed in 1.3.2

thanks!
