### ISSUE TITLE
Trailing whitespace on content

### ISSUE THREAD

**Issue by sofiushko** [rossPatton/stylint#226]
If you have in config `` "trailingWhitespace": "never"`` and in rule ``content: 'foo'`` you'll get ``trailing whitespace``.  But  ``content:'foo'`` will be ok.

**Comment by koffeine** [comment]
It's not just on content, setting trailing whitespace to 'never' also gives warnings on @import declarations:
@import '_base' -> Error: trailing whitespace
@import'_base' -> (without a space between) no error

This issue exists since upgrading to 1.3.2, it was working until then.

**Comment by rossPatton** [comment]
yeah. i know why this is happening, just haven't had time to push a fix.

**Comment by rossPatton** [comment]
this should be fixed in 1.3.3
