### ISSUE TITLE
Error: property is not valid on 1.3.3

### ISSUE THREAD

**Issue by igorfv** [rossPatton/stylint#229]
It's working on 1.3.2, but after the 1.3.3 update it throws an error like:

```
Error: property is not valid
File: src/main.styl
Line: 27: @import 'navigation-header.styl';

[ 'height', '$forms-base-height;' ]
[ 'line-height', '$forms-base-height;' ]
[ 'width', '$forms-base-width;' ]
```

**Comment by rossPatton** [comment]
ugh, i know why. if you remove the semicolon, what happens?

**Comment by rossPatton** [comment]
hey, you want to try updating to 1.3.5 and let me know if you still get this error?

**Comment by igorfv** [comment]
Sorry, I can't easily remove the semicollons, the project is just too big to remove all of them.

Anyway,
I tried with 1.3.5 and the error changed:

```
Error: block variables must include @block
File: src/settings.styl
Line: 23: $font-family = 'Roboto';
```

**Comment by nayaabkhan** [comment]
@igorfv Could you share the `.styl` file causing the trouble?

**Comment by igorfv** [comment]
I'm sorry, I left the company this year and I don't have it anymore, I think it's better to close this issue anyway =/

**Comment by nayaabkhan** [comment]
@igorfv Thanks, please close the issue. 😉
