### ISSUE TITLE
Error: comma must be followed by a space for readability

### ISSUE THREAD

**Issue by Alxblsk** [rossPatton/stylint#232]
Hi, I found that after upgrade from 1.3.2 to 1.3.5 I start receiving an error:

`Error: commas must be followed by a space for readability`
`File: theme/nextgen/hello-world.styl`
`Line: 14: font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;`

my current configuration is 
```javascript
'trailingWhitespace': {
    'expect': 'never',
    'error': true
},
```

Founded, if wrap all font families in double quotes, everything is OK, but it can work only as temporary solution.

**Comment by gscottolson** [comment]
:+1:

**Comment by rossPatton** [comment]
yeah, all these whitespace / comma / etc type issues are really just one bug that's been very hard to squash

**Comment by rossPatton** [comment]
closing because this should (hopefully) be fixed in the latest build
