### ISSUE TITLE
How to ignore some hack rules

### ISSUE THREAD

**Issue by SamZeng** [rossPatton/stylint#262]
Like IE6 `_` and IE7 `*`, I think just support to custom ignore some rules.

Atom version: 1.6.0
Stylint version: 1.2.2

![tips](https://cloud.githubusercontent.com/assets/2367250/13914876/3e9fded0-ef8c-11e5-9d44-216a20beeede.png)

**Comment by rossPatton** [comment]
you might be able to use https://github.com/rossPatton/stylint#transparent-mixin-use--array- to accomplish this

since mixins can be used as properties in stylus you should be to just mark any custom ie properties as 'mixins' and stylus will ignore them
