### ISSUE TITLE
placeholder vs placeholders

### ISSUE THREAD

**Issue by wojciechczerniak** [rossPatton/stylint#275]
Readme says [placeholder](https://github.com/rossPatton/stylint#placeholder--default-always-always--never--false-) but code says [placeholders](https://github.com/rossPatton/stylint/blob/master/src/checks/index.js#L24). An easy fix, but which one is correct? Or both?

**Comment by rossPatton** [comment]
it should be placeholder, thanks for noticing that

**Comment by wojciechczerniak** [comment]
I was working on PR when I realized this can be a breaking change. 

If someone has figured it out and set `placeholders` correctly it will stop working for them. If someone had `placeholder` this check doesn't work for them anyway.

Or we can leave it like that and just adjust readme, other config options: `brackets`, `colons`, `semicolons` are plural too.

**Comment by SimenB** [comment]
Fix readme now, and fix implementation in V2?

**Comment by rossPatton** [comment]
gonna close this, best case scenario might be to just support both names

**Comment by PhiLhoSoft** [comment]
The readme at https://github.com/rossPatton/stylint#options still shows `"placeholders"` which is confusing because when you search this, we don't find it.
