### ISSUE TITLE
´stylint -v´ returns my app version, not Stylint module version

### ISSUE THREAD

**Issue by PalleZingmark** [rossPatton/stylint#29]
This is a minor issue, but I just want you to know about it. :) 

I'm running Stylint local (using Gulp) instead of global, and when I'm doing a versions check I get the version of my app instead of the version of Stylint.

**Comment by rossPatton** [comment]
haha, whoops

easy one to fix

**Comment by rossPatton** [comment]
closing, issue fixed as of 0.8.5
