### ISSUE TITLE
Feature request: Add support for ´namingConvention: BEM´

### ISSUE THREAD

**Issue by PalleZingmark** [rossPatton/stylint#30]
Would be great if there were to be support for BEM as a naming convention in Stylint.

```xml
^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?((_[a-z0-9]([-]?[a-z0-9]+)*){2})?$
```
Pattern source https://github.com/causes/scss-lint/issues/254#issuecomment-59002801

**Comment by rossPatton** [comment]
closing since i merged in your PR
