### ISSUE TITLE
using a url link like "http://a.com" as a mixin parameter will cause line comment warning

### ISSUE THREAD

**Issue by lyt9304** [rossPatton/stylint#302]
We have a mixin using a URL as parameter, when we calling mixin, and pass a URL like:`http://a.com/a.png`. 

Stylint will report a warning like:

~~~
[Warning]: line comments require a space after //
File: css/sem.styl
Line: 76: nav-icon(20px, 'http://a.com/a.png')
~~~

It seems like '//' in 'http://' is recognized as a comment mark

I read the source code, and I found that before check stylint ignore the url in url().

But still need to think about maybe there will be some other place that we will use URL link, and that will cause this problem.

**Comment by rossPatton** [comment]
should be fixed in 1.5.0
