### ISSUE TITLE
Get list of error and warnings with the node api

### ISSUE THREAD

**Issue by vtfn** [rossPatton/stylint#304]
Is there an way to get a list of errors, with the corresponding severity, message e position in the file, using the node api?

**Comment by vtfn** [comment]
never mind. I see I can do what I want using the json reporter

**Comment by vtfn** [comment]
is there a way to get the column where the error has been caught?

**Comment by rossPatton** [comment]
not at the moment

**Comment by rossPatton** [comment]
i have added line columns to _most_ of the checks, closing for now

**Comment by vtfn** [comment]
You've also changed the message formating. Now both my vscode code extension and the stylish reporter are broken. My vscode extension relies on the message formating, the stylish reporter I don't know. I don't care change my extension but it would be good to know if it's possible any future changes in the formating. Would it be possible to keep consistense for now on?

**Comment by SimenB** [comment]
@vtfn What do you mean "broken"?

**Comment by rossPatton** [comment]
hmm, what goes into the reporter function shouldn't have changed. so reporters shouldn't have been affected.

the main change, that I think might be causing your issue, was adding a setting to group the output by file type (groupByFileType). I added it as a config option specifically because I didn't want to break any reporters

when set to false the output is the same as it used to be, when set to true true it is the new format

**Comment by SimenB** [comment]
Stylish reporter should be fixed when #329 is published.

I also added column to stylish reporter in `1.3.0`

**Comment by vtfn** [comment]
@SimenB It's not showing any outputs.

@rossPatton Sorry I can't find where I should set groupByFileType. could you give me a light?

**Comment by SimenB** [comment]
@vtfn Yeah, that'll be fixed when #329 gets published.

WRT to the option, see https://github.com/rossPatton/stylint#options `groupOutputByFile` is there

**Comment by vtfn** [comment]
@SimenB  I that's the one place I didn't look. Thanks and sorry for such a stupid question. Setting this to false dind't help but I think I finally find my way through this problem. Thank you both.

**Comment by SimenB** [comment]
It's `false` by default. But try with the version Ross published 5 minutes ago, it fixes the stylish reporter. If you parse stdout it probably fixes your stuff as well 😄

**Comment by vtfn** [comment]
Yeah. Still don't got it. rs. 
I was going to use the "messages" property in the "cache" object. But it's also new. I really don't care changing my extension as I think there's no excuses to not update the linter. but I if the next versions change again in this manner, I would, again, have to change my extension, and that would not be good.

**Comment by rossPatton** [comment]
i have no intention to make any more changes to the way reporters or the output works

**Comment by vtfn** [comment]
Ok. I will update my extension. I don't have much time to spend thinking in a better way to do it so I will keep relying in the formated messages. Thank you

**Comment by rossPatton** [comment]
no worries, sorry for the trouble
