### ISSUE TITLE
Load stylintrc from package.json?

### ISSUE THREAD

**Issue by FezVrasta** [rossPatton/stylint#308]
With stylelint (and eslint etc) I'm able to load the configuration from the `package.json` file.

How can I do the same with stylint?

Thanks.

**Comment by SimenB** [comment]
No support for it atm

**Comment by rossPatton** [comment]
i will probably add this in 1.4.1

**Comment by rossPatton** [comment]
i've added support for this in 1.5.0, see the readme, let me know if you have any questions
