### ISSUE TITLE
Doesn't support glob paths?

### ISSUE THREAD

**Issue by FezVrasta** [rossPatton/stylint#309]
If I try to use:

    stylint ./app/**/*.styl

it throws an error saying that the file was not found, seems like it doesn't support the syntax?

**Comment by SimenB** [comment]
Hmm, probably not. You can do `stylint app/` though, and the same glob is applied

https://github.com/rossPatton/stylint/blob/master/src/core/read.js#L20

**Comment by FezVrasta** [comment]
Thanks but I need it to support glob to work properly with lint-staged and other stuff...

Any chance to get a fix for it? It seems like the problem is the `fs.stat` function that doesn't support the glob syntax. Couldn't it just use `this.getFiles` when the path is defined?

**Comment by SimenB** [comment]
Probably! Wanna give it a go? PRs welcome 😄

**Comment by FezVrasta** [comment]
Never worked with glob stuff... I'm already trying to get it to work, will send a PR if I end up with something

**Comment by rossPatton** [comment]
@FezVrasta there should be better support for this in the latest version

will re-open if not
