### ISSUE TITLE
false positive: "value on this line could be more succinct"

### ISSUE THREAD

**Issue by tamird** [rossPatton/stylint#314]
Here's the error in question:

Error: the value on this line could be more succinct
File: styl/partials/layout.styl
Line: 540: padding 0 0 20px 0

We worked around it here: https://github.com/cockroachdb/cockroach/pull/6948/files#diff-49afd9210ee083373de7270b062f368bL540

I think this is a false positive because those 0 paddings may override padding from another source earlier in the evaluation order. Am I missing something?

cc @maxlang

**Comment by rossPatton** [comment]
I understand the frustration but this appears to be working as intended. That check basically looks at `padding 0 0 20px 0` and sees that it could be written as `padding 0 0 20px` with the same result. It doesn't have the contextually awareness to know that you are purposely overriding a previous rule.

Your workaround is fine, but you can also make use of the ignore comment like so: `padding 0 0 20px //@stylint ignore`

How do you like mithril?

**Comment by tamird** [comment]
Thanks! That's a bummer.

We don't like it very much - that UI is currently being re-written in react (see ui/next) :)
