### ISSUE TITLE
Is there a .stylintignore or equivalent?

### ISSUE THREAD

**Issue by ucarion** [rossPatton/stylint#319]
I'd love to have something similar to .gitignore, but for excluding certain files from linting.

Edit: I see how that there's an exclude option -- I'm not sure how you'd handle both a .stylintignore and an explicit exclude in .stylintrc

**Comment by rossPatton** [comment]
a `.stylintignore` file is a good idea, in the mean time there is the excludes option as you've noticed

**Comment by rossPatton** [comment]
i have added support for this in 1.4.0, let me know how it works

will re-open if there are issues
