### ISSUE TITLE
SVG text-ancor: middle; css property throws two lint errors

### ISSUE THREAD

**Issue by Kamilius** [rossPatton/stylint#323]
OS: Mac OS X

Styling my inline SVG component with CSS styles and having two errors, which appear for a single line:

`text-anchor: middle;`
```
 line 14:  always use brackets when defining selectors
 line 14:  property is not valid
```

**Comment by rossPatton** [comment]
this'll be fixed in the next release, thanks

**Comment by rossPatton** [comment]
1.4.0 is out, and this issue _should_ be fixed

if not I will re-open
