### ISSUE TITLE
Uncaught exception in 1.4.0

### ISSUE THREAD

**Issue by SimenB** [rossPatton/stylint#324]
Hey @rossPatton 

Greenkeper built my stylint-stylish module against the latest release, and it errors with

```
   17. Uncaught Exception
   TypeError: Cannot read property 'indexOf' of undefined
    Object.<anonymous> (node_modules/stylint/src/core/read.js:38:29)
    Object.<anonymous> (node_modules/stylint/src/core/read.js:44:8)
    FSReqWrap.oncomplete (fs.js:82:15)
```

This change is the cuprit: https://github.com/rossPatton/stylint/commit/023996a60d6b56e3e911563da2bdd78f134f4aca#diff-0ab73be7839ba0db987fd2e8fbe2afa9

I might not initialize stylint correctly in my tests (I haven't had time to look into it), but I thought I'd flag it now

**Comment by SimenB** [comment]
And of course THe quick fix before going to work makes the tests pass

**Comment by EMCP** [comment]
glad this wasn't just me

**Comment by rossPatton** [comment]
1.4.1 is out and should fix this, thanks for flagging
