### ISSUE TITLE
jscs style config

### ISSUE THREAD

**Issue by rossPatton** [rossPatton/stylint#34]
now that features are finally being ironed out a bit, we need to allow for a wider range of config options for a lot of the checks

example: instead of semicolons: bool, it should be semicolons: 'always', 'never', false

where:
'always' === force use of semicolons
'never' === force absence of semicolons
false === don't check for this

**Comment by himedlooff** [comment]
Agreed. Seems weird to have a rule that forces no semicolons, but no option to enforce semicolons.

**Comment by MyFriendBrad** [comment]
+1

This would apply to brackets and colons, right?

**Comment by rossPatton** [comment]
i've always aimed for this to be a potential 1.0 feature, as it might result in breaking changes

**Comment by MyFriendBrad** [comment]
lets get that 1.0 out the door! haha

**Comment by MyFriendBrad** [comment]
If you want some help on this, I might be able to do some work or at least get this started. Any thoughts on how you wanna try an tackle this?

**Comment by rossPatton** [comment]
A lot of it is just identifying which checks it should apply to, and then determining how best to add that functionality. So, most checks that are true false should be change to always/never/false, and some more could have several options that can be passed in as strings (like how naming convention currently works). 

So I think the first step is identifying which checks it would make sense to take this approach with. This would probably go hand in hand with a general refactor, as I imagine most checks would benefit from this.

And then of course, heavily communicating the change as much as possible.

Right now the checks are very single purpose, and adding the ability to enforce an opposite rule would basically double them in size, so it might sense to actually break many of the checks into separate small functions (always, never) and then just calling the appropriate one based on what the configuration is set to. Create a potentially long-lived branch and merge develop into it often so the eventual merge is less painful.

Ii'm mostly a front end guy actually, so If you have a better suggestion on how to approach this i'm all ears.

**Comment by kizu** [comment]
+1 here, jscs-style config would make it easier to implement things like #98. `leadingZero` would be then split to `disallowLeadingZero` and `requireLeadingZero` etc.
