### ISSUE TITLE
Gulp Wrapper

### ISSUE THREAD

**Issue by rossPatton** [rossPatton/stylint#38]
create an easy to use (pipable) wrapper for gulp

**Comment by jwilsson** [comment]
Hi!
Just wanted to let you know that I'd be more than happy to help out with a Gulp plugin.

Let me know how you want to approach it, if you want to do something or just leave it to me :wink:

**Comment by rossPatton** [comment]
Hey man,

I'm pretty swamped lately so I haven't had much time to work on stylint. 

So, just do whatever you want here, thanks!

Just let me know if there's anything I can help you with.

**Comment by jwilsson** [comment]
Alright, awesome!

I'll see if I get something up and running this weekend.

**Comment by danielhusar** [comment]
Hey I can create gulp task if nobody has started working on it yet.

**Comment by jwilsson** [comment]
@danielhusar I'm afraid I haven't had the time (and it looks like it will be a while before I will, some things came up) so from my point feel free to take it :)

**Comment by danielhusar** [comment]
Cool :)

I have created one: https://github.com/danielhusar/gulp-stylint
Let me know if you have any improvements or issues there :)

**Comment by rossPatton** [comment]
@danielhusar Awesome! Thanks man! Can't wait to check it out.

**Comment by danielhusar** [comment]
I can add you to collaborators if you want to :) So you can bump dependencies in future.

**Comment by rossPatton** [comment]
@danielhusar Sure
