### ISSUE TITLE
namingConvention strictness level ?

### ISSUE THREAD

**Issue by rossPatton** [rossPatton/stylint#44]
this was brought up in another issue, that you won't always have full control over class names or ids.

in this case, namingConvention will throw lots of warnings at you that are out of your control

we could create a config settings that allows to toggle the breadth of the namingConvention option.

if `namingConventionStrict: true` is set, then namingConvention will target classes and ids as well as variables. if set to false, then it will only care about variables

**Comment by rossPatton** [comment]
@awayken

**Comment by awayken** [comment]
:+1: I like this proposal.

If someone is using their own personal rules for CSS classes and IDs but still wants to enforce a naming convention on their Stylus variables, they can set this to "false." If they want all CSS and Stylus to be enforced the same way, they can set this to "true." And if they want strict enforcement but have a spot or two where they're dealing with third party conventions, they can use the `@stylint off` toggle around that third-party code.

I think that makes everyone happy.

**Comment by rossPatton** [comment]
available in 0.9.3
