### ISSUE TITLE
Unicode emoji in "done" logs render as empty boxes on Windows

### ISSUE THREAD

**Issue by awayken** [rossPatton/stylint#55]
I honestly had no idea that you *nix users get a :+1: when things are all clear. On Windows, there's just an empty box.

This is what I see on Windows:
![image](https://cloud.githubusercontent.com/assets/156215/6690742/4640fe5a-cc90-11e4-9954-df430616436c.png)

I'll submit a pull request that I think can address this, although I'm open to ideas on how to do it in a better way. I'll explain more in the PR.

**Comment by freeformsystems** [comment]
I would suggest removing the emoji(s) completely various fonts will not render these (on UNIX) and it is quite distracting (my font (http://www.fsd.it/fonts/pragmatapro.htm) does not include these glyphs).

You could use ANSI sequences instead to differentiate success and failure.

**Comment by rossPatton** [comment]
emoji / icons will be off by default in the next update

there will be an option to toggle them back on

**Comment by rossPatton** [comment]
closing as this is available in 0.9.3
