### ISSUE TITLE
Respect exit code

### ISSUE THREAD

**Issue by freeformsystems** [rossPatton/stylint#57]
Please respect the UNIX exit code philosophy, zero on success and greater than zero on error.

It appears to me that the program always exits with zero, looking at https://github.com/rossPatton/stylint/blob/master/src/done.js it should be easy to implement with the caveat that watch mode would need to be tested to ignore calling `process.exit`.

**Comment by camjc** [comment]
:+1: Am trying to put stylint in as a pre-commit hook now and this would be the preferred behavior for me.

**Comment by rossPatton** [comment]
will do, thanks for making me aware of this

**Comment by rossPatton** [comment]
if you check out the develop branch, it should now output an error code of 1 if stylint finds any error, and 2 if you set an error limit and go over it

please verify

**Comment by rossPatton** [comment]
this is in 0.9.3
