### ISSUE TITLE
`duplicates: true` doesn't play nicely with listing multiple selectors on newlines without commas

### ISSUE THREAD

**Issue by camjc** [rossPatton/stylint#58]
If I write
```
foo
bar
  height: 10px

foo
  color: red
```

It thinks that I'm selecting foo twice.

Stylint works perfectly if I write (notice the comma after the first `foo`):
```
foo,
bar
  height: 10px

foo
  color: red
```

**Comment by rossPatton** [comment]
personally i would suggest always using the comma here, but i will look into this

**Comment by matthojo** [comment]
+1 for this.

The comma separated version could even be another option for the linter.

**Comment by benedfit** [comment]
:+1:
