### ISSUE TITLE
borderNone doesnt take colon into consideration

### ISSUE THREAD

**Issue by MyFriendBrad** [rossPatton/stylint#78]
In correlation with an enhancement ticket (https://github.com/rossPatton/stylint/issues/34), there needs to be consideration for if the user is enforcing colons or not. In the case of borderNone, its looking for "border none" not "border: none" therefore it is passing tests even if set to true.

**Comment by rossPatton** [comment]
very doable

**Comment by rossPatton** [comment]
this should be fixed in 0.9.3
