### ISSUE TITLE
Support alternative property ordering style

### ISSUE THREAD

**Issue by benedfit** [rossPatton/stylint#88]
We've been reviewing the default settings here at @clocklimited, and agreeing internally on what we want to enable and disable. Discussions around alphabetical property ordering led us to https://css-tricks.com/poll-results-how-do-you-order-your-css-properties/ where the majority of those polled voted in favour of grouping by type. We still couldn't agree internally on whether we'd prefer to group by type or order alphabetically, but we did agree that having a tool to enforce whichever approach was essential.

So to that end, would you be interested in us contributing a feature that allows users to override property ordering if they don't want to use alphabetical ordering? [CSScomb](https://github.com/csscomb/csscomb.js/blob/master/config/csscomb.json#L28-L327) and [RECESS from Twitter](https://github.com/twitter/recess/blob/master/lib/lint/strict-property-order.js) have similar features that could be borrowed from, but I wanted to check if this was of interest before we started

**Comment by rossPatton** [comment]
Well, it wasn't something I was considering but the general idea with stylint is to be agnostic about how people write their css. 

I personally don't sort by type (how do you ever decide what order to put things in?) but if there's already an implementation of this feature out there I don't see why this can't be in stylint.

I work on this in my spare time, so I can't give you an estimate of how soon the feature will be available, but i'll update this thread when it is.

In the meantime, you could just disable alphabetical sorting.

**Comment by awayken** [comment]
@benedfit Would the idea be to literally pass in the preferred ordering into Stylint? Or would it still be a choice between distinct styles (alphabetical, type, none)?

**Comment by benedfit** [comment]
@rossPatton seeing as we're the ones asking for it, we would be happy to create the feature in a Pull Request for you to review if you like?

@awayken we'd envisaged that the current `alphabetical` option would change to `sortorder`, which would then accept one of three values:

* `alphabetical` the default
* `grouped` which would match properties against a predetermined list (perhaps we could use the one from RECESS as a base given that it's used by Bootstrap) e.g:
  * https://github.com/csscomb/csscomb.js/tree/master/config
  * https://github.com/twitter/recess/blob/master/lib/lint/strict-property-order.js#L36
* or an array of properties that would allow users to specify their own groupings if they didn't like the defaults

**Comment by rossPatton** [comment]
@benedfit If you guys want to do the implementation i'd gladly review it. Else it'd probably take me a week or two to get around to it.

**Comment by benedfit** [comment]
Just a heads up that I started working on this today

**Comment by rossPatton** [comment]
awesome!

**Comment by danielbayley** [comment]
Wouldn't it be better to make use of existing solutions like _[csscomb]_ or _[postcss-sorting]_ for this?

[csscomb]: https://npmjs.com/package/csscomb
[postcss-sorting]: https://npmjs.com/package/postcss-sorting

**Comment by benedfit** [comment]
From our perspective we were after a standard way of ordering as we write, rather than when the CSS is published, so we'd want it to be a pre-compilation thing rather than something handled by postcss.

The solution I put forward used csscomb as the basis for the order, but if you can think of a better way of doing it that I did, I'm happy to go with it
