### ISSUE TITLE
Efficient: true does nothing if you have colons

### ISSUE THREAD

**Issue by camjc** [rossPatton/stylint#91]
`    margin: 3px 0 3px 0`
won't error, but
`    margin 3px 0 3px 0`
will error as it should.

Thanks for the awesome tool!

**Comment by rossPatton** [comment]
Thank you for reporting the bug, i'll get this fixed in the next update

**Comment by camjc** [comment]
Thanks mate! Will update our version of stylint on monday at work. I really appreciate all the work you've been putting in on this project.
