### ISSUE TITLE
List Stylint code editor linter plugins

### ISSUE THREAD

**Issue by matthojo** [rossPatton/stylint#93]
I think it would be handy to list available stylint editor linter plugins somewhere.

These are the 2 I know of so far;

@jackbrewer built: https://github.com/jackbrewer/SublimeLinter-contrib-stylint
I built: https://github.com/AtomLinter/linter-stylint

**Comment by jackbrewer** [comment]
Slightly premature for the Sublime one - still getting it through the Sublime Linter approval process so it can be installed directly from the Package Manager within Sublime. Should be done soon though.

**Comment by rossPatton** [comment]
@jackbrewer Thanks for that btw! I've been using it recently and it works great

**Comment by jackbrewer** [comment]
Not a problem, happy to help! It was recently accepted so should now be available through the Sublime Package Manager. It's been working well so far. It mainly relies on a regex to parse the CLI results (as does @matthojo 's Atom version) so we should only need to update them if the default output formatting ever changes.

**Comment by rossPatton** [comment]
@matthojo @matthojo If you guys want, feel free to make a PR and just update the readme yourselves with anything you find.
