### ISSUE TITLE
nodejs api to use without cli

### ISSUE THREAD

**Issue by Coobaha** [rossPatton/stylint#99]
It will be awesome to have nodejs module, for usage without cli

**Comment by rossPatton** [comment]
:+1: this is a feature i'll probably add for 1.0

**Comment by rossPatton** [comment]
@Coobaha https://github.com/rossPatton/stylint/issues/108

**Comment by rossPatton** [comment]
Technically, this has always been possible but wasn't intuitive. It should now work more intuitively in 1.0 (which is out), see the docs.
